### 게시글 작성
POST http://localhost:8080/articles
Content-Type: application/json

{
  "title": "blog title",
  "content": "blog content"
}

### 게시글 조회 API
GET http://localhost:8080/articles

### 게시글 단건 조회 API
@id=3
GET http://localhost:8080/articles/{{id}}

### 게시글 단건 삭제 API
DELETE http://localhost:8080/articles/{{id}}

### 게시글 단건 수정 API
PUT localhost:8080/articles/{{id}}
Content-Type: application/json

{
  "title": "변경된 제목",
  "content": "변경된 내용"
}